# Generated by Django 4.2.2 on 2024-12-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="название")),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="модель"
                    ),
                ),
                (
                    "release_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата выхода"
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
